"""
Generate a Unity editor script that copies a vanilla item's hand poses (GripPose objects and their
finger bones) onto the selected prefab root.

    python make_handpose_script.py <vanilla.bundle> <MenuName> [output.cs]

Example:

    python make_handpose_script.py foregrip_all_zenit_b25u_rk_1.bundle RK1B25U ../unity/AddRK1B25UHandPoses.cs

Copy the .cs file into the SDK project's Assets/Editor/ folder; it adds
Tools > Add <MenuName> Hand Poses. Needs Python 3 and UnityPy (pip install UnityPy).
"""

import sys

import UnityPy

GRIP_TYPES = ["Common", "Alternative", "UnderbarrelWeapon"]


def read_poses(path):
    env = UnityPy.load(path)
    objs = {o.path_id: o for o in env.objects}
    gos = {pid: o.read_typetree() for pid, o in objs.items() if o.type.name == "GameObject"}
    transforms = {pid: o.read_typetree() for pid, o in objs.items() if o.type.name == "Transform"}
    behaviours = {pid: o.read_typetree() for pid, o in objs.items() if o.type.name == "MonoBehaviour"}

    def node(pid):
        t = transforms[pid]
        go = gos[t["m_GameObject"]["m_PathID"]]
        grip = None
        for c in go["m_Component"]:
            mb = behaviours.get(c["component"]["m_PathID"])
            if mb and "GripType" in mb:
                grip = mb
        return {
            "name": go["m_Name"],
            "pos": list(t["m_LocalPosition"].values()),
            "rot": list(t["m_LocalRotation"].values()),
            "grip": grip,
            "children": [node(ch["m_PathID"]) for ch in t["m_Children"]],
        }

    root = next(pid for pid, t in transforms.items() if t["m_Father"]["m_PathID"] == 0)
    return [child for child in node(root)["children"] if child["grip"]]


def literal(value):
    return f"{float(value)!r}f"


def emit(lines, node, parent, var):
    pos = ", ".join(literal(v) for v in node["pos"])
    rot = ", ".join(literal(v) for v in node["rot"])
    lines.append(f'        var {var} = Bone({parent}, "{node["name"]}", new Vector3({pos}), new Quaternion({rot}));')
    if node["grip"]:
        g = node["grip"]
        lines.append(f'        AddGripPose({var}, (EDoorState){g["DoorState"]}, (GripPose.EHand){g["Hand"]}, '
                     f'(GripPose.EGripType){g["GripType"]});')
    for i, child in enumerate(node["children"]):
        emit(lines, child, var, f"{var}_{i}")


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    bundle, menu = sys.argv[1], sys.argv[2]
    out = sys.argv[3] if len(sys.argv) > 3 else f"Add{menu}HandPoses.cs"
    poses = read_poses(bundle)
    if not poses:
        sys.exit("No GripPose objects found in that bundle.")

    lines = []
    for i, pose in enumerate(poses):
        lines.append(f'        // {pose["name"]}: GripType {GRIP_TYPES[pose["grip"]["GripType"]]}')
        emit(lines, pose, "root", f"palm{i}")
    cls = f"Add{menu}HandPoses"
    first = poses[0]["name"]
    source = f'''using EFT.Interactive;
using UnityEditor;
using UnityEngine;

// Generated by tools/make_handpose_script.py from {bundle.replace(chr(92), "/").split("/")[-1]}.
// Adds that item's hand poses (GripPose objects and finger bones) to the selected prefab root.
// Put this file in Assets/Editor/ of the SDK project.
public static class {cls}
{{
    [MenuItem("Tools/Add {menu} Hand Poses")]
    private static void Add()
    {{
        var root = Selection.activeTransform;
        if (root == null)
        {{
            EditorUtility.DisplayDialog("Hand poses", "Select your item's root object first.", "OK");
            return;
        }}
        if (root.Find("{first}") != null)
        {{
            EditorUtility.DisplayDialog("Hand poses", "This object already has these hand poses.", "OK");
            return;
        }}

        Undo.SetCurrentGroupName("Add {menu} hand poses");
{chr(10).join(lines)}

        Debug.Log($"Added {menu} hand poses to {{root.name}}. Move the palm objects onto your model, then apply the prefab.");
    }}

    private static Transform Bone(Transform parent, string name, Vector3 localPosition, Quaternion localRotation)
    {{
        var bone = new GameObject(name).transform;
        Undo.RegisterCreatedObjectUndo(bone.gameObject, "Add {menu} hand poses");
        bone.SetParent(parent, false);
        bone.localPosition = localPosition;
        bone.localRotation = localRotation;
        return bone;
    }}

    private static void AddGripPose(Transform palm, EDoorState doorState, GripPose.EHand hand, GripPose.EGripType gripType)
    {{
        var pose = Undo.AddComponent<GripPose>(palm.gameObject);
        pose.DoorState = doorState;
        pose.Hand = hand;
        pose.GripType = gripType;
    }}
}}
'''
    with open(out, "w") as f:
        f.write(source)
    print(f"Wrote {out} with {len(poses)} hand pose(s): {', '.join(p['name'] for p in poses)}")


if __name__ == "__main__":
    main()
